apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-cache
  namespace: default
  labels:
    app.kubernetes.io/name: remote-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: remote-cache
  template:
    metadata:
      labels:
        app.kubernetes.io/name: remote-cache
    spec:
      containers:
      - name: remote-cache
        image: buchgr/bazel-remote-cache:latest
        ports:
          - containerPort: 9092
            name: grpc
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
        livenessProbe:
            grpc:
              service: /grpc.health.v1.Health/Check
              port: 9092
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
        readinessProbe:
            grpc:
              service: /grpc.health.v1.Health/Check
              port: 9092
            failureThreshold: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 10
        env:
        - name: BAZEL_REMOTE_DIR
          value: /data
        - name: BAZEL_REMOTE_MAX_SIZE
          value: "1000"

---

apiVersion: v1
kind: Service
metadata:
  name: remote-cache
spec:
  selector:
    app.kubernetes.io/name: remote-cache
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
