apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-cluster-us-west-2"

  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      volumeSize: 100Gi
      volumeType: gp3
      encrypted: true

  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: "cluster-us-west-2"

  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "cluster-us-west-2"

---

apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: g4dn
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 600s
  template:
    metadata:
      labels:
        april.dev/accelerator: "nvidia-t4-16gb"
        nvidia.com/gpu: "true"
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - g4dn
      taints:
      - key: nvidia.com/gpu
        value: "true"
        effect: "NoSchedule"

---

apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: g5
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 600s
  template:
    metadata:
      labels:
        april.dev/accelerator: "nvidia-a10g-24gb"
        nvidia.com/gpu: "true"
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
        - g5
      taints:
      - key: nvidia.com/gpu
        value: "true"
        effect: "NoSchedule"

---

apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: t3
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 600s
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.k8s.aws/instance-family
        operator: In
        values:
          - t3
