FROM docker.io/python:3-slim

ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
RUN mkdir /app && useradd --create-home app
WORKDIR /app
COPY . .

USER app
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT [ "python", "./runner.py" ]
